server:
  port: 8080

spring:
  application:
    name: springai-enterprise-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_db
    username: ai_user
    password: ai_pass
  flyway:
    enabled: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE
        dimensions: 1536
        schema-name: public
        table-name: embeddings

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
