replicaCount: 2
image:
  repository: your-registry/springai-enterprise-demo
  tag: "1.0.0"
env:
  OPENAI_API_KEY: ""
  DB_USER: "ai_user"
  DB_PASSWORD: "ai_pass"
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
