apiVersion: apps/v1
kind: Deployment
metadata:
  name: springai-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: springai-demo
  template:
    metadata:
      labels:
        app: springai-demo
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: apiKey
            - name: DB_USER
              value: "{{ .Values.env.DB_USER }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          resources:
{{ toYaml .Values.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: springai-demo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: springai-demo
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
