apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
stringData:
  apiKey: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  password: "ai_pass"
