services:
  app:
    build: .
    image: springai-enterprise-demo:1.0.0
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_USER=ai_user
      - DB_PASSWORD=ai_pass
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=ai_user
      - POSTGRES_PASSWORD=ai_pass
      - POSTGRES_DB=ai_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_user -d ai_db"]
      interval: 5s
      timeout: 5s
      retries: 20
